In [3]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [21]:
# To reshape the array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) # # 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [24]:
# Create Array With inbuild Functions
np.arange(0,10,2) # Craete an array (initialization,range,increment)

array([0, 2, 4, 6, 8])

In [25]:
# Onces
np.ones((3,4)) #(row,columns)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
# No of bytes that array using to find out
arr1.itemsize

4

In [30]:
# Numpy Vectorized Operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element wise addition
print(arr1+arr2)

# Element wise Subraction
print(arr1-arr2)

# Element wise Multiplication
print(arr1*arr2)

# Element wise Divison
print(arr1/arr2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [31]:
# Universal Function
arr1=np.array([1,2,3])

# Squre Root
print(np.sqrt(arr1))

#Exponential 
print(np.exp(arr1))

#Sine Value
print(np.sin(arr1))

# Natural log
print(np.log(arr1))




[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]
[0.         0.69314718 1.09861229]


In [33]:
# Array Slicing and Indexing

arr  = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
arr[0:,2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [44]:
# Statistical Operations
# Noramalization 

arr = np.array([1,2,3,4,5])
x_min = min(arr)
x_max = max(arr)

result = []

# Formula (x-x_min)/(x_max-x_min)
for x in arr:
    result.append((x-x_min)/(x_max-x_min))
print(result)

[0.0, 0.25, 0.5, 0.75, 1.0]


In [48]:
# calculate the mean and std deviation of the data
mean  = np.mean(arr)
std_dev = np.std(arr)
varience = np.var(arr)
standadization  = (arr - mean)/std_dev

print(mean)
print(std_dev)
print(standadization)
print(varience)

#From the Standardization Value to find out the mean is 0 and std deviation is 1 
print(np.mean(standadization))
print(np.std(standadization))


3.0
1.4142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
2.0
0.0
0.9999999999999999


In [55]:
# Logical Operations
arr>2

array([False, False,  True,  True,  True])

In [56]:
arr[(arr>2)]

array([3, 4, 5])